# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZnSB6yL_10SURmB7ctifdlMW3MjmUx2A
"""

# ================== ICTS MULTI-AGENT PATH FINDING WITH SAVING ==================

from heapq import heappush, heappop
from collections import defaultdict
import itertools, random, os
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.animation import FuncAnimation, PillowWriter
from google.colab import drive

# --- Mount Google Drive ---
drive.mount('/content/drive')

# --- Output directory ---
save_dir = "/content/drive/MyDrive/ICTS_Results"
os.makedirs(save_dir, exist_ok=True)

# --- Grid helpers ---
DIRS = [(0,1),(1,0),(0,-1),(-1,0)]

def in_bounds(grid, x, y): return 0 <= x < len(grid) and 0 <= y < len(grid[0])
def is_free(grid, x, y): return in_bounds(grid, x, y) and grid[x][y] == 0
def manhattan(a,b): return abs(a[0]-b[0]) + abs(a[1]-b[1])

# --- A* shortest path ---
from heapq import heappush, heappop
def astar_shortest_length(grid, start, goal):
    openq = []
    gscore = {start: 0}
    fscore = {start: manhattan(start,goal)}
    heappush(openq, (fscore[start], start))
    visited = set()
    while openq:
        f, cur = heappop(openq)
        if cur in visited: continue
        visited.add(cur)
        if cur == goal: return gscore[cur]
        for dx,dy in DIRS:
            nx,ny = cur[0]+dx, cur[1]+dy
            if not is_free(grid, nx, ny): continue
            tentative = gscore[cur] + 1
            if tentative < gscore.get((nx,ny), 1e9):
                gscore[(nx,ny)] = tentative
                fscore[(nx,ny)] = tentative + manhattan((nx,ny), goal)
                heappush(openq, (fscore[(nx,ny)], (nx,ny)))
    return None

# --- Enumerate all paths of given length (MDD) ---
def enumerate_paths_of_length(grid, start, goal, length, max_paths=None):
    mdd = defaultdict(set)
    mdd[0].add(start)
    for t in range(length):
        for x, y in list(mdd[t]):
            for dx, dy in DIRS + [(0,0)]:
                nx, ny = x+dx, y+dy
                if is_free(grid, nx, ny):
                    mdd[t+1].add((nx, ny))
    reachable_from_goal = defaultdict(set)
    reachable_from_goal[length].add(goal)
    for t in reversed(range(length)):
        for x, y in list(mdd[t]):
            for dx, dy in DIRS + [(0,0)]:
                nx, ny = x+dx, y+dy
                if (nx, ny) in reachable_from_goal[t+1]:
                    reachable_from_goal[t].add((x, y))
                    break
        mdd[t] &= reachable_from_goal[t]

    paths = []
    def dfs(pos, t, path):
        if t == length:
            if pos == goal:
                paths.append(path[:])
            return
        for dx, dy in DIRS + [(0,0)]:
            nx, ny = pos[0]+dx, pos[1]+dy
            if (nx, ny) in mdd[t+1]:
                dfs((nx, ny), t+1, path + [(nx, ny)])
                if max_paths and len(paths) >= max_paths:
                    return
    dfs(start, 0, [start])
    return paths

# --- Collision checking ---
def detect_collision(paths):
    num_agents = len(paths)
    max_t = max(len(p) for p in paths) - 1
    padded = []
    for p in paths:
        if len(p) - 1 < max_t:
            last = p[-1]
            padded.append(p + [last] * (max_t - (len(p)-1)))
        else:
            padded.append(p)
    for t in range(max_t+1):
        pos_time = defaultdict(list)
        for i in range(num_agents):
            pos_time[padded[i][t]].append(i)
        for pos, agents in pos_time.items():
            if len(agents) > 1:
                return True
    for t in range(max_t):
        edge_time = {}
        for i in range(num_agents):
            a_from, a_to = padded[i][t], padded[i][t+1]
            edge_time[i] = (a_from, a_to)
        for i,j in itertools.combinations(range(num_agents), 2):
            if edge_time[i][0] == edge_time[j][1] and edge_time[i][1] == edge_time[j][0]:
                return True
    return False

# --- Backtracking to combine paths ---
def combine_agent_paths_backtracking(all_agent_paths):
    n = len(all_agent_paths)
    chosen = [None]*n
    def backtrack(i):
        if i == n:
            return chosen.copy() if not detect_collision(chosen) else None
        for p in all_agent_paths[i]:
            chosen[i] = p
            if not detect_collision(chosen[:i+1]):
                res = backtrack(i+1)
                if res is not None:
                    return res
            chosen[i] = None
        return None
    return backtrack(0)

# --- ICTS main search ---
def ict_search(grid, agents, max_paths_per_agent=2000):
    n = len(agents)
    min_costs = []
    for (s,g) in agents:
        l = astar_shortest_length(grid, s, g)
        if l is None:
            print(f"Agent {s}->{g} unreachable.")
            return None
        min_costs.append(l)
    pq = []
    visited = set()
    start_tuple = tuple(min_costs)
    heappush(pq, (sum(start_tuple), start_tuple))
    visited.add(start_tuple)
    while pq:
        total, cost_tuple = heappop(pq)
        all_agent_paths = []
        feasible = True
        for (s,g), cost_i in zip(agents, cost_tuple):
            paths_i = enumerate_paths_of_length(grid, s, g, cost_i, max_paths_per_agent)
            if not paths_i:
                feasible = False; break
            all_agent_paths.append(paths_i)
        if not feasible:
            for i in range(n):
                new = list(cost_tuple); new[i]+=1
                newt = tuple(new)
                if newt not in visited:
                    visited.add(newt)
                    heappush(pq, (sum(newt), newt))
            continue
        sol = combine_agent_paths_backtracking(all_agent_paths)
        if sol is not None:
            return {"paths": sol, "cost": total}
        for i in range(n):
            new = list(cost_tuple); new[i]+=1
            newt = tuple(new)
            if newt not in visited:
                visited.add(newt)
                heappush(pq, (sum(newt), newt))
    return None

# --- Visualization and Save ---
def visualize_and_save(grid, paths, filename, interval=400):
    n_rows, n_cols = len(grid), len(grid[0])
    n_agents = len(paths)
    max_t = max(len(p) for p in paths)
    fig, ax = plt.subplots(figsize=(n_cols/1.5, n_rows/1.5))
    ax.set_xlim(0, n_cols)
    ax.set_ylim(0, n_rows)
    ax.set_xticks(range(n_cols+1))
    ax.set_yticks(range(n_rows+1))
    ax.grid(True)
    ax.invert_yaxis()
    ax.set_aspect('equal')
    for i in range(n_rows):
        for j in range(n_cols):
            if grid[i][j] == 1:
                ax.add_patch(patches.Rectangle((j, i), 1, 1, color='black'))
    cmap = plt.cm.get_cmap('tab10', n_agents)
    colors = [cmap(i) for i in range(n_agents)]
    circles = []
    for idx in range(n_agents):
        c = plt.Circle((paths[idx][0][1]+0.5, paths[idx][0][0]+0.5), 0.3, color=colors[idx], alpha=0.8)
        ax.add_patch(c)
        circles.append(c)
    def update(frame):
        for idx, c in enumerate(circles):
            if frame < len(paths[idx]):
                x, y = paths[idx][frame]
            else:
                x, y = paths[idx][-1]
            c.center = (y+0.5, x+0.5)
        ax.set_title(f"t={frame}")
        return circles
    ani = FuncAnimation(fig, update, frames=max_t, interval=interval, blit=True)
    save_path = os.path.join(save_dir, filename)
    ani.save(save_path, writer=PillowWriter(fps=1000//interval))
    print(f"✅ Saved animation to: {save_path}")
    plt.close(fig)

# --- Visualization and Save ---
def visualize_and_save(grid, paths, starts, goals, filename, interval=400):
    n_rows, n_cols = len(grid), len(grid[0])
    n_agents = len(paths)
    max_t = max(len(p) for p in paths)

    fig, ax = plt.subplots(figsize=(n_cols/1.5, n_rows/1.5))
    ax.set_xlim(0, n_cols)
    ax.set_ylim(0, n_rows)
    ax.set_xticks(range(n_cols+1))
    ax.set_yticks(range(n_rows+1))
    ax.grid(True)
    ax.invert_yaxis()
    ax.set_aspect('equal')

    # Draw obstacles
    for i in range(n_rows):
        for j in range(n_cols):
            if grid[i][j] == 1:
                ax.add_patch(patches.Rectangle((j, i), 1, 1, color='black'))

    # Draw start & goal markers
    cmap = plt.cm.get_cmap('tab10', n_agents)
    colors = [cmap(i) for i in range(n_agents)]

    for idx, (s, g) in enumerate(zip(starts, goals)):
        sx, sy = s
        gx, gy = g
        ax.add_patch(patches.Circle((sy + 0.5, sx + 0.5), 0.3,
                                    edgecolor='green', facecolor=colors[idx], lw=2, alpha=0.6))
        ax.add_patch(patches.RegularPolygon((gy + 0.5, gx + 0.5), numVertices=5, radius=0.4,
                                            orientation=0, edgecolor='red', facecolor=colors[idx], lw=2, alpha=0.6))

    # Agent circles (for animation)
    circles = []
    for idx in range(n_agents):
        c = plt.Circle((paths[idx][0][1]+0.5, paths[idx][0][0]+0.5), 0.25, color=colors[idx], alpha=0.9)
        ax.add_patch(c)
        circles.append(c)

    # Update function
    def update(frame):
        for idx, c in enumerate(circles):
            if frame < len(paths[idx]):
                x, y = paths[idx][frame]
            else:
                x, y = paths[idx][-1]
            c.center = (y+0.5, x+0.5)
        ax.set_title(f"t = {frame}")
        return circles

    ani = FuncAnimation(fig, update, frames=max_t, interval=interval, blit=True)
    save_path = os.path.join(save_dir, filename)
    ani.save(save_path, writer=PillowWriter(fps=1000//interval))
    print(f"✅ Saved animation to: {save_path}")
    plt.close(fig)



# --- Run experiments and save each result ---
def run_experiments():
    configs = [
        (2, 10),
        (5, 20),
        (8, 20),
        (10, 20),
        (12, 40)
    ]

    for num_agents, grid_size in configs:
        print(f"\n=== Running ICTS: {num_agents} agents on {grid_size}x{grid_size} grid ===")

        # Create grid with random obstacles
        obstacle_prob = 0.15 if grid_size <= 20 else 0.20
        grid = [[1 if random.random() < obstacle_prob else 0 for _ in range(grid_size)] for _ in range(grid_size)]

        starts, goals, taken = [], [], set()
        for _ in range(num_agents):
            while True:
                s = (random.randint(0, grid_size-1), random.randint(0, grid_size-1))
                g = (random.randint(0, grid_size-1), random.randint(0, grid_size-1))
                # ensure start/goal not on obstacle or already taken
                if grid[s[0]][s[1]] == 0 and grid[g[0]][g[1]] == 0 and s not in taken and g not in taken and s != g:
                    taken.add(s)
                    taken.add(g)
                    starts.append(s)
                    goals.append(g)
                    break

        agents = list(zip(starts, goals))
        sol = ict_search(grid, agents, max_paths_per_agent=3000)

        if sol:
            print(f"Found solution. Total cost = {sol['cost']}")
            filename = f"ICTS_{num_agents}agents_{grid_size}x{grid_size}.gif"
            visualize_and_save(grid, sol['paths'], starts, goals, filename)
        else:
            print("No solution found or search too costly.")


# --- MAIN ---
if __name__ == "__main__":
    run_experiments()